# Generated by Django 6.1.1 on 2026-09-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'permissions': [('manage_staff_accounts', 'Can manage staff accounts')]},
        ),
    ]
